In [1]:
import sys
import numpy as np
from scipy.ndimage import label
import matplotlib.pyplot as plt

matrix = np.array([
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 1, 1, 1, 0, 0, 1, 1, 0, 0],
    [0, 1, 1, 1, 0, 0, 1, 1, 0, 0],
    [0, 1, 1, 1, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 1, 1, 0, 0, 1, 1, 1, 0],
    [0, 0, 1, 1, 0, 0, 1, 1, 1, 0],
    [0, 0, 0, 0, 0, 0, 1, 1, 1, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
])

structure = np.array([[0, 1, 0],
                      [1, 1, 1],
                      [0, 1, 0]])

labeled_array, num_features = label(matrix, structure=structure)

print("Jumlah objek berdasarkan 4-connectivity:", num_features)

plt.figure(figsize=(6, 6))
plt.imshow(labeled_array, cmap='nipy_spectral')
plt.title("Hasil Labeling 4-Connectivity", fontsize=14, pad=15)
plt.colorbar(label='ID Objek')
plt.axis('on')
plt.show()

Matriks Objek:
 [[0 0 0 0 0 0 0 0 0 0]
 [0 1 1 1 0 0 1 1 0 0]
 [0 1 1 1 0 0 1 1 0 0]
 [0 1 1 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 1 1 0 0 1 1 1 0]
 [0 0 1 1 0 0 1 1 1 0]
 [0 0 0 0 0 0 1 1 1 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]

Jumlah objek berdasarkan 4-connectivity: 4
